# Generated by Django 5.0.1 on 2024-11-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='patients',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='authentication.patientprofile'),
        ),
    ]
