# Generated by Django 5.0.1 on 2024-11-20 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_prediction_treatmentplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='medical_record',
        ),
        migrations.AddField(
            model_name='testresult',
            name='blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='chest_pain_type',
            field=models.CharField(blank=True, choices=[('TA', 'Typical Angina'), ('ATA', 'Atypical Angina'), ('NAP', 'Non-Anginal Pain'), ('ASY', 'Asymptomatic')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='exercise_angina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='fasting_bs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='insulin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='max_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.patientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='resting_ecg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='skin_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
