# Generated by Django 5.0.1 on 2024-11-21 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_testresult_medical_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(default='002', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='authentication.patientprofile'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='blood_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='chest_pain_type',
            field=models.CharField(choices=[('TA', 'Typical Angina'), ('ATA', 'Atypical Angina'), ('NAP', 'Non-Anginal Pain'), ('ASY', 'Asymptomatic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='cholesterol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='exercise_angina',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='fasting_bs',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='glucose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='insulin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='max_hr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='resting_ecg',
            field=models.CharField(choices=[('Normal', 'Normal'), ('ST', 'ST-T Wave Abnormality'), ('LVH', 'Left Ventricular Hypertrophy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='skin_thickness',
            field=models.FloatField(),
        ),
    ]
