# Generated by Django 5.1.2 on 2024-11-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentplan',
            old_name='primary_treatment',
            new_name='primary_recommendation',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='follow_up_schedule',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='medications',
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='detailed_plan',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.patientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='warnings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.prediction'),
        ),
    ]
