# Generated by Django 5.1.2 on 2024-11-24 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_primary_treatment_treatmentplan_primary_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('test_results', 'New Test Results Available'), ('appointment', 'Appointment Reminder/Update'), ('critical_alert', 'Critical Patient Alert'), ('prescription', 'Prescription Update'), ('patient_update', 'Patient Information Update'), ('treatment_plan', 'Treatment Plan Update')], default='patient_update', max_length=50),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('lab', 'Laboratory'), ('patient', 'Patient Room'), ('surgery', 'Surgery Room'), ('icu', 'ICU'), ('emergency', 'Emergency Room'), ('consultation', 'Consultation Room')], default='patient', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField(default=1)),
                ('equipment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Being Cleaned'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_rooms', to='authentication.doctorprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rooms', to='authentication.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.doctorprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.patientprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.room')),
            ],
        ),
    ]
